import React from 'react';

import Head from 'next/head';
import Link from 'next/link';
import InformationModal from '../components/InformationModal';

import text from './text.json';

export default function Home() {
  return (
    <>
      <Head>
        <title>Cosmic Carrots</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]'>
        <div className='container flex flex-col items-center justify-center gap-12 px-4 py-16 '>
          <h1 className='text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]'>
            Cosmic
            {' '}
            <span className='text-purple-600'>Carrots</span>
            {' '}
            Idle Game
          </h1>
          <div className='flex flex-col items-center justify-center gap-4 max-w-[750px]'>
            <p className='text-xl font-light text-center text-white'>
              {text.header.subtitle}
            </p>
            <div className='flex py-6 items-center justify-center gap-4'>
              <button
                className='px-4 py-2 text-lg font-semibold text-white bg-purple-600 rounded-md'
                type='button'
              >
                <Link href='/play'>Start Game</Link>
              </button>

              <InformationModal />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
